apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spotiplay

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: spotiplay
    newTag: latest

labels:
  - pairs:
      version: latest
    includeSelectors: false
